# Generated by Django 4.2 on 2024-04-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='synopsis',
            new_name='description',
        ),
    ]
